### ISSUE TITLE
Usage of UpdatePath in LabHostDefaults

### ISSUE THREAD

**Issue by ryanspletzer** [VirtualEngine/Lability#77] opened 2016-03-22 23:53 UTC
This is more of a question: I see in the Lab Host Defaults there's an UpdatePath key with an empty path value. I don't really see anywhere else in the code (besides in getting / setting lab host defaults) where this is used.

Is the idea that you would put offline Windows Updates in this folder and Lability would apply them? Is the functionality implemented to do this or is still a feature to be added?

**Comment by iainbrighton** [comment] 2016-03-23 18:33
@ryanspletzer Correct - it's not implemented yet. The "plan" was/is to enable automatic installation of Windows updates into the parent VHD. However, there may be some tie-up with https://github.com/BladeFireLight/WindowsImageTools in future for creating patched master/parent images. Is there any other PowerShell solution out there for patching VHD(X)s?

**Comment by ryanspletzer** [comment] 2016-03-27 20:01
Hmm yeah that's a tricky and interesting problem to work through...

Even getting a list of Windows updates for a given media is a tricky, too. The only sure fire tool I've seen for that is an executable from http://www.wsusoffline.net/ but no PowerShell based solutions. 

Get-WUList from the PSWindowsUpdate module in the gallery uses COM to get a list of updates for the machine you're on, and in *theory* for a remote computer you specify with -ComputerName (although didn't seem to get remote to work for me).

**Comment by iainbrighton** [comment] 2016-03-27 22:18
@ryanspletzer Ha! At least I use WSUSOffline too :wink:. The problem is made more tricky by the fact that some updates cannot be applied offline; .NET Framework and IE updates come to mind. That's why I've not implemented it yet.

I'm still not sure on if and how it should be implemented..

**Comment by it-praktyk** [comment] 2016-03-28 06:01
@iainbrighton Maybe [Hyper-V Image Factory](https://github.com/BenjaminArmstrong/Hyper-V-PowerShell/tree/master/Image-Factory) can be used to create/maintain the base images?

**Comment by iainbrighton** [comment] 2016-03-28 09:52
I was not aware of that and will take a look.

The more I think about this, I actually think it could/should be the "update" scripts/modules that leverage Lability to create patched images! Whilst Lability could be extended to support this, it's not its primary purpose. I also wouldn't want to add another solution to the ones that are available.

Custom/patched images can be used with Lability today. This is how I use Lability - I have my own patched eval and VL media created and registered.

Thoughts?

**Comment by ryanspletzer** [comment] 2016-03-29 01:48
I think that actually makes more sense, to create the patched / sysprepped media and register it. This is what's done in practice anyways in our virtual environments.

**Comment by it-praktyk** [comment] 2016-03-30 06:37
Yes, I agree - this can be done using Hyper-V Image Factory.

`PS \Image-Factory> .\Factory.ps1
22:52 - [Windows Server 2012 R2 DataCenter with GUI]::Starting a new cycle!
22:52 - [Windows Server 2012 R2 DataCenter with GUI]::Checking for existing Factory VM
22:52 - [Windows Server 2012 R2 DataCenter with GUI]::No base VHD!
22:52 - [Windows Server 2012 R2 DataCenter with GUI]::Creating unattend file for base VHD
22:52 - [Windows Server 2012 R2 DataCenter with GUI]::Create base VHD using Convert-WindowsImage.ps1

Windows(R) Image to Virtual Hard Disk Converter for Windows(R) 10
Copyright (C) Microsoft Corporation.  All rights reserved.
Version 10.0.9000.0.amd64fre.fbl_core1_hyp_dev(mikekol).141224-3000 Beta


INFO   : Image 4 selected (ServerDataCenter)...
INFO   : Creating sparse disk...
INFO   : Attaching VHDX...
INFO   : Disk initialized with MBR...
INFO   : Disk partitioned...
INFO   : Volume formatted...
INFO   : Access path (F:\) has been assigned...
INFO   : Applying image to VHDX. This could take a while...
INFO   : Applying unattend file (unattend.xml)...
INFO   : Signing disk...
INFO   : Image applied. Making image bootable...
INFO   : Fixing the Device ID in the BCD store on VHDX...
INFO   : Drive is bootable. Cleaning up...
INFO   : Closing VHDX...

INFO   : Closing Windows image...
INFO   : Done.
22:56 - [Windows Server 2012 R2 DataCenter with GUI]::Remove unattend file now that that is done
22:56 - [Windows Server 2012 R2 DataCenter with GUI]::Mount VHD and copy bits in, also set startup file
22:56 - [Windows Server 2012 R2 DataCenter with GUI]::Create virtual machine, start it and wait for it to stop...
02:48 - [Windows Server 2012 R2 DataCenter with GUI]::Removing the page file
02:48 - [Windows Server 2012 R2 DataCenter with GUI]::Compacting the base file
02:49 - [Windows Server 2012 R2 DataCenter with GUI]::Need to run Sysprep
02:49 - [Windows Server 2012 R2 DataCenter with GUI]::Creating differencing disk
02:49 - [Windows Server 2012 R2 DataCenter with GUI]::Mount the differencing disk and copy in files
02:49 - [Windows Server 2012 R2 DataCenter with GUI]::Create virtual machine, start it and wait for it to stop...
02:57 - [Windows Server 2012 R2 DataCenter with GUI]::Mount the differencing disk and cleanup files
02:57 - [Windows Server 2012 R2 DataCenter with GUI]::Removing the page file
02:57 - [Windows Server 2012 R2 DataCenter with GUI]::Convert differencing disk into pristine base image
03:04 - [Windows Server 2012 R2 DataCenter with GUI]::Optimizing VHD file
03:04 - [Windows Server 2012 R2 DataCenter with GUI]::Delete differencing disk
03:04 - [Windows Server 2012 R2 DataCenter Core]::Starting a new cycle!
03:04 - [Windows Server 2012 R2 DataCenter Core]::Checking for existing Factory VM
03:04 - [Windows Server 2012 R2 DataCenter Core]::No base VHD!
03:04 - [Windows Server 2012 R2 DataCenter Core]::Creating unattend file for base VHD
03:04 - [Windows Server 2012 R2 DataCenter Core]::Create base VHD using Convert-WindowsImage.ps1

Windows(R) Image to Virtual Hard Disk Converter for Windows(R) 10
Copyright (C) Microsoft Corporation.  All rights reserved.
Version 10.0.9000.0.amd64fre.fbl_core1_hyp_dev(mikekol).141224-3000 Beta


INFO   : Image 3 selected (ServerDataCenterCore)...

<CUT>

`

**Comment by iainbrighton** [comment] 2016-04-01 08:29
@it-praktyk Just to confirm that Lability will already create base images from ISO media
- This is needed to be able to bootstrap VMs from scratch with Evaluation media, if required
- Some of the code used was adapted from the MSFT Convert-WindowsImage script
- It can inject some DSC specific hotfixes where defined in the media configuration
- You can use and register your own patched .WIM/VHD(X) files if needed (this is what I do!)

__I don't think that we should implement creating or updating fully patched VHD(X) images within this module.__ There are plenty of scripts/modules that already try to do this. Most people will want to bring their own base images anyway! Agreed?

**Comment by ryanspletzer** [comment] 2016-04-03 21:00
Agreed!

**Comment by iainbrighton** [comment] 2016-04-03 21:07
Can you reopen the issue to make sure we remove the setting/parameter? Thanks!

**Comment by ryanspletzer** [comment] 2016-04-03 21:16
Yep!

**Closed** 2016-04-06 08:57 UTC
