### ISSUE TITLE
Using Invoke-LabResourceDownload doesn't save into versioned folder for DSC Resources

### ISSUE THREAD

**Issue by kilasuit** [VirtualEngine/Lability#90] opened 2016-04-12 01:08 UTC
Imagine the Scenario - you are working on multiple different labs and have to switch between them frequently
These labs are using different versions of the DSC Resources and you may have to rebuild them at any time.
Currently the DSCResources Modules are being saved directly in the Module folder root and not the version number subfolder as you would expect.

So you could remove the DSCResources from the C:\Program Files\WindowsPowerShell\Modules\ location and call Invoke-LabResource each time you need to rebuild however this is inefficient and the Invoke-LabResourceDownload should mirror the expectations from Save/Install-Module to place in correct versioned subfolder.

I believe the fix would be in the InvokeDscResourceDownloadFromPSGallery internal function where it is currently

``` powershell
$tempModuleFilename = '{0}.zip' -f $Name;
```

though I reckon should be

``` powershell
If ($MinimumVersion) {$moduleVersion = $MinimumVersion} else {$moduleVersion = $RequiredVersion}
$tempModuleFilename = '{0}.{1}.zip' -f $Name,$moduleVersion
```

though at the same time this would be a good line to change too

``` powershell
$modulePath = Join-Path $windowsPowerShellModules -ChildPath $Name;
```

to

``` powershell
$modulePath = Join-Path $windowsPowerShellModules -ChildPath "$Name\$moduleVersion";
```

Example of how this is acting is as below 

![labilityerror2](https://cloud.githubusercontent.com/assets/6355225/14446605/e1079892-004f-11e6-951c-62b2e9fbb530.PNG)

**Comment by iainbrighton** [comment] 2016-04-12 10:23
@kilasuit Yes - but that will break v4 compatibility :-1:. I'm thinking about dropping Win 8.1/2012 R2 compatibility (or forking the project) when 2016 is generally available: NAT, nested Hyper-V and PowerShell are too tempting from a lab perspective. Until then... Thoughts?

**Comment by kilasuit** [comment] 2016-04-24 14:28
Perhaps as a way to support both it may make more sense to add in another switch for v4/v5 compatibility.

That way it allows both ways?

**Comment by iainbrighton** [comment] 2016-04-24 20:27
I'm sure that we could add the logic to behave as intended based on the version of PowerShell running on the host.

Currently we're enumerating the locally installed modules. There is no reason to change this to just using cached/downloaded .ZIP files (and not actually installing them on the host). Would this be of benefit though if you don't already have compiled .mofs?

**Comment by iainbrighton** [comment] 2016-10-19 21:12
@kilasuit Can this now be closed as multiple DSC resources and module versions were implemented in 0.10.0 - although in a slightly different way to the suggestion here?

**Comment by quizard** [comment] 2016-10-23 19:05
Hey Iain, could you help me understand the change? I was using something I wrote to install dependent modules when I stumbled across invoke-labresourcedownload. What script/function picks up the downloaded zips and allows injection into the configuration for import-resource please? Do I need to loop through and unzip to my modules directory? Thank you sir, I haven't had this much fun in years with build automation!

**Comment by iainbrighton** [comment] 2016-10-23 20:39
Hi @quizard - I'm glad you're enjoying things! Here is what was implemented in 0.10.0:

* Lability no longer downloads or installs DSC resource/modules into the `C:\Program Files\WindowsPowerShell\Modules` folder.
* Lability now downloadeds and __caches (not install)__ in the Lability `ModuleCachePath` directory.
 * This permits using different DSC resource module versions in different configurations/VMs.
* When creating VMs, the cached module is expanded in to the VMs VHDX.

The side effect of this approach is that as the DSC resources are no longer installed on the host machine - ___you'll need to manually install the DSC resources if you want to compile the .mof file(s).___ This is the issue described in #147 and will be addressed in #153. Does this answer your immediate question?

/cc @kilasuit @csandfeld In the short term you can do this to install the modules from the Lability module cache onto the host machine:
```powershell
## Import the module and get a reference
$lability = Import-Module -Name Lability -Force -PassThru

## Call private function to convert the configuration data to a hashtable as we need to get the required DSC resources.
$configData = & $lability { ConvertToConfigurationData .\Examples\NanoComputeExample.psd1 }

## Call private function to install the modules into the host's module path
& $lability { ExpandModuleCache -Module $configData.NonNodeData.Lability.DSCResource -DestinationPath 'C:\Program Files\WindowsPowerShell\Modules' }

    Directory: C:\Program Files\WindowsPowerShell\Modules

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       23/10/2016     21:30                xNetworking
d-----       23/10/2016     21:30                xPSDesiredStateConfiguration
```

**Comment by kilasuit** [comment] 2016-11-13 21:12
I agree that this was the right decision
>     Lability no longer downloads or installs DSC resource/modules into the C:\Program Files\WindowsPowerShell\Modules folder.

However, I'd be more suggestive to make the move to add the Module Cache location to the process scope of PSModulePath as this would allow it to be a relatively non-invasive change and is blown away when we kill/close the current process or sooner if we decide that is a better option (I think it would be) - however with this we would likely need to expand the DSC Resource modules into that location by default (not a bad idea either)

I am however pondering when it would be right to do this as we need this done to be able to compile the mof's prior to when we run Start-LabConfiguration which makes me think of the following options

- At Module Load (simple at do but not always going to be needed)

- Within an additional function that wraps around the process of mof compilation as opposed to how we both seem to be doing it similar to https://github.com/iainbrighton/PSDEVOPS/blob/master/PSDEVOPS_Demo.ps1#L51 

Thoughts?

**Comment by quizard** [comment] 2017-03-29 19:27
Now that ConvertToConfigurationData and ExpandModuleCache are missing functions, what is the suggested way to drop the cached modules in place now? I have a 7zip script but I'm thinking you have a better way :) .

**Comment by iainbrighton** [comment] 2017-03-30 20:25
@quizard They're still there? ConvertToConfigurationData has moved and is now https://github.com/VirtualEngine/Lability/blob/dev/Src/Private/ConvertTo-ConfigurationData.ps1. ExpandModuleCache is where it's always been https://github.com/VirtualEngine/Lability/blob/dev/Lib/Module.ps1#L627-L757 ?

**Comment by iainbrighton** [comment] 2017-08-16 13:16
@kilasuit Is this issue still valid now that all modules are versioned and cached (instead of stored in the PSModulePath)?

**Comment by iainbrighton** [comment] 2017-10-17 13:24
Closing out - reopen if it still needs discussion!

**Closed by iainbrighton** 2017-10-17 13:24 UTC
Labels: enhancement, question
